config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles
  resources :posts
  resources :requests

  root 'pages#home'
  get '/about' => 'pages#about'
  get '/donations' => 'pages#donations'
  get '/news' => 'pages#news'
  get '/contact' => 'pages#icontact'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image,
    :path => ":rails_root/public/system/:attachment/:id/:basename_:style.:extension",
    :url => "/system/:attachment/:id/:basename_:style.:extension",

    :styles => {
      :mini     => ['50x50#',    :jpg, :quality => 70],
      :thumb    => ['100x100#',  :jpg, :quality => 70],
      :small    => ['150x150#',  :jpg, :quality => 70],
      :medium   => ['200x200#',  :jpg, :quality => 70],
      :preview  => ['480x480#',  :jpg, :quality => 70],
      :large    => ['600>',      :jpg, :quality => 70],
      :retina   => ['1200>',     :jpg, :quality => 30]
    },

    :convert_options => {
      :mini     => '-set colorspace sRGB -strip',
      :thumb    => '-set colorspace sRGB -strip',
      :small    => '-set colorspace sRGB -strip',
      :medium   => '-set colorspace sRGB -strip',
      :preview  => '-set colorspace sRGB -strip',
      :large    => '-set colorspace sRGB -strip',
      :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
    }

    validates_attachment :image,
      :presence => true,
      :size => { :in => 0..10.megabytes },
      :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }

    has_attached_file :landscape,
      :path => ":rails_root/public/system/:attachment/:id/:basename_:style.:extension",
      :url => "/system/:attachment/:id/:basename_:style.:extension",

      :styles => {
        :regular    =>  ['1200x300#',  :jpg, :quality => 70]
      },

      :convert_options => {
        :regular    =>  '-set colorspace sRGB -strip'
      }

      validates_attachment :landscape,
        :presence => true,
        :size => {:in => 0..10.megabytes},
        :content_type => {:content_type => /^image\/(jpeg|png|gif|tiff)$/ }
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: [:edit, :update, :show, :destroy]

  def index
    @profiles = Profile.all
    @posts = Post.all
  end

  def new
    if current_user.profile.nil?
      @profile = Profile.new
    else
      redirect_to profiles_path
    end
  end

  def edit
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    @profile.email = current_user.email
    @profile.username = current_user.username
    if @profile.save
      flash[:success] = "Profile was sucessfully created"
      redirect_to profiles_path
    else
      render 'new'
    end
  end

  def update
    if @profile.update(profile_params)
      flash[:success] = "Profile was successfully updated"
      redirect_to profile_path(@profile)
    else
      render 'edit'
    end
  end

  def show
    @posts = Post.all
  end

  def destroy
    @profile.destroy
    flash[:danger] = "Profile was successfully deleted"
    redirect_to profile_path
  end

  private

    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:name, :last_name, :birth_date, :biography, :country, :city, :phone_number, :cell_phone, :blood_type, :image, :occupation, :landscape)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
<div class="pink-text text">
  <div class="row">
    <div class="col s6 push-s3">
      <div class="card-panel white">
        <div class="row">
          <div class="input-field col s6">
            <i class="material-icons prefix">account_circle</i>
            <%= f.label :name, "Nombre" %>
            <%= f.text_field :name %>
          </div>
          <div class="input-field col s6">
            <i class="material-icons prefix">account_circle</i>
            <%= f.label :last_name, "Apellido" %>
            <%= f.text_field :last_name %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <i class="material-icons prefix">work</i>
            <%= f.label :occupation, "Ocupación" %>
            <%= f.text_field :occupation %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <i class="material-icons prefix">mode_edit</i>
            <%= f.label :biography, "Cuentanos sobre ti" %>
            <%= f.text_area :biography, class:"materialize-textarea" %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s6">
            <i class="material-icons prefix">cake</i>
            <%= f.label :birth_date, "Fecha de Nacimiento" %>
            <%= f.text_field :birth_date, class: "datepicker"%>
          </div>
          <div class="input-field col s6">
            <%= f.select(:blood_type, ['O+','O-','A+','A-','B+','B-','AB+','AB-'], label:"Tipo De Sangre")%>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s6">
            <i class="material-icons prefix">place</i>
            <%= f.label :country, "Pais" %>
            <%= f.text_field :country %>
          </div>
          <div class="input-field col s6">
            <i class="material-icons prefix">place</i>
            <%= f.label :city, "Ciudad" %>
            <%= f.text_field :city %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s6">
            <i class="material-icons prefix">phone</i>
            <%= f.label :phone_number, "Numero de Teléfono" %>
            <%= f.text_field :phone_number %>
          </div>
          <div class="input-field col s6">
            <i class="material-icons prefix">smartphone</i>
            <%= f.label :cell_phone, "Celular" %>
            <%= f.text_field :cell_phone %>
          </div>
        </div>
        <div class="row">
          <div class="input field col s12 center">
            <i class="material-icons prefix">mood</i>
            <%= f.label :image, "Foto de Perfil" %>
            <%= f.file_field :image, class: 'form-control'%>
          </div>
        </div>
        <div class="row">
          <div class="input field col s12 center">
            <i class="material-icons prefix">mood</i>
            <%= f.label :landscape, "Foto de Fondo" %>
            <%= f.file_field :landscape, class: 'form-control'%>
          </div>
        </div>

        <div class="row">
          <div class="col s12 center">
            <%= f.submit "Aceptar", class:"btn pink" %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% end %>
</div>

app/views/profiles/edit.html.erb
<h1 class="pink-text text center">Editar Perfil</h1>

<%= render 'form' %>

app/views/profiles/index.html.erb
<body>
  <%if current_user.profile == nil %>
  <div class="container">
    <div class="col s6 push-s3 center">
    </br>
      <%= image_tag("social-3.png", :alt=>"social", size:"150x150")%>
    </br>
      <h3> Todavía no has creado un perfil. Personaliza tu espacio haciendo click en Crear Perfil </h3>
      <%= link_to 'Crear mi perfil', new_profile_path, class:"btn pink" %>
    </div>
  </div>
  <%else%>
  <% @profiles.each do |profile| %>
  <%if current_user.id == profile.user_id %>
</br>
<div class="row">
  <div class="col s12">
    <div class="card" style="height:500px">
      <div class="card-image waves-effect waves-block waves-light">
        <span class="card-title activator grey-text text-darken-4"><i class="material-icons right">more_vert</i></span>
        <%= image_tag profile.landscape.url(:regular), class:"activator"%>
      </div>
      <div class="card-content">
        <div class="row">
          <div class="col s3 center">
            <a href="#"><%= image_tag profile.image.url(:small), class:"circle z-depth-3 modal-trigger", href:"#modal1"%></a>
          </div>
          <div class="col s3 center">
            <h5 class="pink-text text"><%=profile.name%> <%=profile.last_name%></h5>
            <h6 class="pink-text text">@<%=profile.username%></h6>
            <h6 class="pink-text text-lighten-2"><%=profile.occupation%><h6>
            </div>
            <div class="col s3 center">
              <h5 class="pink-text text"><%=profile.blood_type%></h5>
              <h6 class="pink-text text-lighten-2">Tipo de Sangre</h6>
            </div>
            <div class="col s3 center">
              <h5 class="pink-text text"><%=profile.city%>,<%=profile.country%></h5>
              <h6 class="pink-text text-lighten-2">Residencia</h6>
            </br></br>
            <%= link_to 'Editar Mi Perfil', edit_profile_path(profile), class:"btn pink"%>
          </div>
        </div>
      </div>
      <div class="card-reveal pink-text text">
        <div class="row">
          <span class="card-title"><i class="material-icons right">close</i></span>
          <h3><%= profile.name %> <%= profile.last_name%></h3></br>
          <h5><i class="material-icons">work</i><%=profile.occupation%></h5></br>
          <h5><i class="material-icons">phone</i> <%=profile.phone_number%> | <i class="material-icons">stay_current_portrait</i> <%=profile.cell_phone%></h5></br>
          <h5><i class="material-icons">email</i> <%=current_user.email%></h5></br>
          <h5><i class="material-icons">cake</i> <%=profile.birth_date%> </h5>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s4">
    <div class="card-panel white">
      <span class="pink-text">
        <h5>Acerca de Mi</h5><hr>
        <%=profile.biography%>
        <hr>
        Miembro desde: <%= current_user.created_at.to_date.to_formatted_s :long_ordinal %>
      </span>
    </div>
  </div>

  <div class="col s8">
    <div class="card-panel white">
      <span class="pink-text text">
        <%= form_for(Post.new) do |f| %>
        <div class="row">
          <div class="input-field col s12">
            <i class="material-icons prefix">mode_edit</i>
            <%= f.label :body, "Escribe un post" %>
            <%= f.text_area :body, class:"materialize-textarea" %>
          </div>
        </div>
        <div class="row">
          <div class="col s12 center">
            <%= f.submit "Aceptar", class:"btn pink" %>
          </div>
        </div>
        <%end%>
      </span>
    </div>
  </div>
</div>
<div class="row">
  <div class="col s8 push-s4">
    <h4 class="pink-text text">Posts</h4>
    <ul class="collection">
    <% @posts.each do |post| %>
      <% if post.user_id == current_user.id %>
        <li class="collection-item avatar">
          <%=image_tag profile.image.url(:mini), class:"circle z-depth-3"%>
          <span class="title"><%= link_to profile.username,profile_path(profile)%></span>
          <p><p class="grey-text text-lighten-1"><%=time_ago_in_words(post.created_at)%> ago</p><br>
             <%=post.body%>
          </p>
          <a href="#!" class="secondary-content pink-text text"><i class="material-icons">clear</i></a>
        </li>
      <%end%>
    <%end%>
    </ul>
  </div>
</div>


<div id="modal1" class="modal", style="height:600px">
  <div class="modal-content center">
    <%=image_tag profile.image.url(:preview)%>
  </div>
</div>
<% end %>
<% end %>
<% end %>
</body>

app/views/profiles/new.html.erb
<h1 class="pink-text text center">Nuevo Perfil</h1>

<%= render 'form' %>

app/views/profiles/show.html.erb
<div class="row">
  <div class="col s12">
    <div class="card" style="height:500px">
      <div class="card-image waves-effect waves-block waves-light">
        <span class="card-title activator grey-text text-darken-4"><i class="material-icons right">more_vert</i></span>
        <%= image_tag @profile.landscape.url(:regular), class:"activator"%>
      </div>
      <div class="card-content">
        <div class="row">
          <div class="col s3 center">
            <a href="#"><%= image_tag @profile.image.url(:small), class:"circle z-depth-3 modal-trigger", href:"#modal1"%></a>
          </div>
          <div class="col s3 center">
            <h5 class="pink-text text"><%=@profile.name%> <%=@profile.last_name%></h5>
            <h6 class="pink-text text-lighten-2"><%=@profile.occupation%><h6>
            </div>
            <div class="col s3 center">
              <h5 class="pink-text text"><%=@profile.blood_type%></h5>
              <h6 class="pink-text text-lighten-2">Tipo de Sangre</h6>
            </div>
            <div class="col s3 center">
              <h5 class="pink-text text"><%=@profile.city%>,<%=@profile.country%></h5>
              <h6 class="pink-text text-lighten-2">Residencia</h6>
            </br></br>
          </div>
        </div>
      </div>
      <div class="card-reveal pink-text text">
        <div class="row">
          <span class="card-title"><i class="material-icons right">close</i></span>
          <h3><%= @profile.name %> <%= @profile.last_name%></h3></br>
          <h5><i class="material-icons">work</i><%=@profile.occupation%></h5></br>
          <h5><i class="material-icons">phone</i> <%=@profile.phone_number%> | <i class="material-icons">stay_current_portrait</i> <%=@profile.cell_phone%></h5></br>
          <h5><i class="material-icons">email</i> <%=@profile.email%></h5></br>
          <h5><i class="material-icons">cake</i> <%=@profile.birth_date%> </h5>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s4">
    <div class="card-panel white">
      <span class="pink-text">
        <h5>Acerca de Mi</h5><hr>
        <%=@profile.biography%>
        <hr>
        Joined on: <%= current_user.created_at.to_date.to_formatted_s :long_ordinal %>
      </span>
    </div>
  </div>

  <div class="col s8">
    <h4 class="pink-text text">Posts</h4>
    <ul class="collection">
    <% @posts.each do |post| %>
      <% if post.user_id == @profile.user_id %>
        <li class="collection-item avatar">
          <%=image_tag @profile.image.url(:mini), class:"circle z-depth-3"%>
          <span class="title"><%= link_to @profile.name, profile_path(@profile)%></span>
          <p><p class="grey-text text-lighten-1"><%=time_ago_in_words(post.created_at)%> ago</p><br>
             <%=post.body%>
          </p>
          <a href="#!" class="secondary-content"><i class="material-icons">clear</i></a>
        </li>
      <%end%>
    <%end%>
    </ul>
  </div>
</div>