config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles
  resources :posts
  resources :requests

  root 'pages#home'
  get '/about' => 'pages#about'
  get '/donations' => 'pages#donations'
  get '/news' => 'pages#news'
  get '/contact' => 'pages#icontact'

end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)
    @request.user_id = current_user.id
    @request.email = current_user.email
    if @request.blood_type_needed == "A+"
      @request.compatible_blood_types = "A+,A-,O+,O-"

    elsif @request.blood_type_needed == "B+"
      @request.compatible_blood_types = "B+,B-,O+,O-"

    elsif @request.blood_type_needed == "AB+"
      @request.compatible_blood_types = "A+,B+,AB+,O+,A-,B-,AB-,O-"

    elsif @request.blood_type_needed == "O+"
      @request.compatible_blood_types = "O+,O-"

    elsif @request.blood_type_needed == "A-"
      @request.compatible_blood_types = "A-,O-"

    elsif @request.blood_type_needed == "B-"
      @request.compatible_blood_types = "B-,O-"

    elsif @request.blood_type_needed == "AB-"
      @request.compatible_blood_types = "A-,B-,AB-,O-"

    elsif @request.blood_type_needed == "O-"
      @request.compatible_blood_types = "O-"
    end
    if @request.save
      flash[:success] = "Request was sucessfully created"
      redirect_to requests_path
    else
      render 'new'
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:name, :phone_number, :email, :needed_for, :blood_type_needed, :blood_units_needed, :date_needed, :compatible_blood_types, :message)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>
      <ul>
      <% @request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col s8 push-s2">
      <div class="card white">
        <div class="card-content pink-text">
          <div class="row">
            <div class="input-field col s8">
              <i class="material-icons prefix">person</i>
              <%= f.label :name, "Nombre Del Solicitante" %><br>
              <%= f.text_field :name, class:"validate" %>
            </div>
            <div class="input-field col s4">
              <i class="material-icons prefix">lens</i>
              <%= f.label :needed_for, "Sangre necesitada para:" %><br>
              <%= f.select(:needed_for, ['Mi mismo','Otra persona']) %>
            </div>
          </div>
          <div class="row">
            <div class="input-field">
              <i class="material-icons prefix">phone</i>
              <%= f.label :phone_number, "Numero De Teléfono" %><br>
              <%= f.text_field :phone_number %>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s4">
              <i class="material-icons prefix">exposure_plus_1</i>
              <%= f.label :blood_units_needed, "No. de Pintas Necesitadas" %><br>
              <%= f.text_field :blood_units_needed %>
            </div>
            <div class="input-field col s4">
              <i class="material-icons prefix">colorize</i>
              <%= f.label :blood_type_needed, "Tipo de Sangre Necesitado" %><br>
              <%= f.select(:blood_type_needed, ['O+','O-','A+','A-','B+','B-','AB+','AB-']) %>
            </div>
            <div class="input-field col s4">
              <i class="material-icons prefix">insert_invitation</i>
              <%= f.label :date_needed, "Fecha Requerida" %><br>
              <%= f.text_field :date_needed, class: "datepicker" %>
            </div>
          </div>
          <div class="row">
            <div class="input-field">
              <i class="material-icons prefix">message</i>
              <%= f.label :message, "Cuentanos tu historia" %><br>
              <%= f.text_area :message, class:"materialize-textarea" %>
            </div>
          </div>
          <div class="row">
            <div class="actions center">
            </br>
              <%= f.submit 'Ingresar Solicitud', class:"pink btn" %>
            </div>
          </div>
        </div>
        <div class="card-action">
            <%= link_to 'Regresar', requests_path, class:"pink-text text"%>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1 class="center pink-text text">Editar Solicitud</h1>

<%= render 'form' %>

app/views/requests/index.html.erb
<h3 class="center pink-text text">Solicitudes de Sangre</h3>

<div class="container pink-text text">
      <ul class="collapsible popout" data-collapsible="accordion">
      <% @requests.each do |request| %>
        <li>
          <div class="collapsible-header"><i class="material-icons">favorite</i> Solicitud de Sangre hecha por: <%=request.name%>
            <% if current_user.id == request.user_id %>
            <div class="right">
              <%= link_to "Borrar", request, method: :delete, data: { confirm: 'Are you sure?' }, class:"pink-text text" %> |
              <%= link_to "Editar", edit_request_path(request), class:"pink-text text" %>
            </div>
            <% end %>
          </div>
          <div class="collapsible-body">
            <div class="container">
            </br>
              <ul>
                <li><i class="material-icons prefix">person</i> <strong>Nombre del Solicitante: </strong> <%=request.name%></li></br>
                <li><i class="material-icons prefix">phone</i>  <strong>Telefono del Solicitante: </strong> <%=request.phone_number%></li></br>
                <li><i class="material-icons prefix">mail</i>   <strong>Email del Solicitante: </strong> <%=request.email%></li></br>
                <li><i class="material-icons prefix">lens</i>   <strong>Tipo de Solicitud: </strong> <%=request.needed_for%></li></br>
                <li><i class="material-icons prefix">colorize</i>  <strong>Tipo de Sangre Necesitado: </strong> <%=request.blood_type_needed%></li></br>
                <li><i class="material-icons prefix">exposure_plus_1</i>  <strong>Pintas de Sangre Necesitadas: </strong> <%=request.blood_units_needed%></li></br>
                <li><i class="material-icons prefix">insert_invitation</i>  <strong>Fecha Requerida: </strong> <%=request.date_needed%></li></br>
                <li><i class="material-icons prefix">favorite_border </i><strong>Tipos de Sangre Compatibles: </strong> <%=request.compatible_blood_types%></li></br>
                <li><i class="material-icons prefix">message </i><strong>Historia: </strong> </br><%=request.message%></li>
              </ul>
            </br>
            </div>
          </div>
        </li>
      <% end %>
      </ul>
</div>
<br>

app/views/requests/new.html.erb
<h1 class="center pink-text text">Nueva Solicitud</h1>

<%= render 'form' %>

app/views/requests/show.html.erb
<h3 class="pink-text text center">Solicitud de Sangre</h3>

<div class="container">
  <p>
    <strong class="pink-text text">Nombre de Contacto:</strong>
    <%= @request.name %>
  </p>

  <p>
    <strong class="pink-text text">Teléfono de Contacto:</strong>
    <%= @request.phone_number %>
  </p>

  <p>
    <strong class="pink-text text">Email:</strong>
    <%= @request.email %>
  </p>

  <p>
    <strong class="pink-text text">Se necesita para:</strong>
    <%= @request.needed_for %>
  </p>

  <p>
    <strong class="pink-text text">Tipo de sangre solicitado:</strong>
    <%= @request.blood_type_needed %>
  </p>

  <p>
    <strong class="pink-text text">Pintas de Sangre necesitadas:</strong>
    <%= @request.blood_units_needed %>
  </p>

  <p>
    <strong class="pink-text text">Fecha requerida:</strong>
    <%= @request.date_needed %>
  </p>

  <p>
    <strong class="pink-text text">Tipos de Sangre Compatibles:</strong>
    <%= @request.compatible_blood_types %>
  </p>

  <p>
    <strong class="pink-text text">Mensaje:</strong>
    <%= @request.message %>
  </p>
  <%= link_to 'Regresar', requests_path, class:"btn pink" %>
</div>