config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles
  resources :posts
  resources :requests

  root 'pages#home'
  get '/about' => 'pages#about'
  get '/donations' => 'pages#donations'
  get '/news' => 'pages#news'
  get '/contact' => 'pages#icontact'

end

app/views/layouts/_footer.html.erb
<% if controller_name == "pages" %>
<footer class="light-blue page-footer">
  <div class="container">
    <div class="row">
      <div class="col s4">
        <h5 class="white-text">Misión</h5>
        <p class="grey-text text-lighten-4">Concientizar a la población Hondureña sobre la escases de donantes a nivel nacional donde prácticamente cualquier
          persona puede ser donante o receptor, creando así oportunidades de vida para todas aquellas personas que se ven en una dificultad médica.</p>
      </div>
      <div class="col s4">
        <h5 class="white-text">Visión</h5>
        <p class="grey-text text-lighten-4">Bleed Me  liderará el camino de Honduras hacia el futuro de una contracultura brindando esperanza y  enriqueciendo vidas por medio de
          donaciones con los  métodos más seguros y responsables para las personas que las necesitan.</p>
      </div>
      <div class="col s4">
        <h5 class="white-text">Enlaces Legales</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#">Términos y Condiciones</a></li>
          <li><a class="grey-text text-lighten-3" href="#">Póliza de Privacidad (Privacy Policy)</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright" style="height:60px;">
    <div class="container">
    Copyright © 2016 BleedMe. Todos los derechos reservados.
    <a class="grey-text text-lighten-4 right" href="https://www.facebook.com/BleedMe-217927415225409/" style="padding-bottom:0;"><%= image_tag("facebook.png", :alt=>"facebook", size:"30x30")%></a>
    <a class="grey-text text-lighten-4 right" href="#!"><%= image_tag("twitter.png", :alt=>"twitter", size:"30x30")%></a>
    <a class="grey-text text-lighten-4 right" href="#!"><%= image_tag("instagram.png", :alt=>"instagram", size:"30x30")%></a>
    </div>
  </div>
</footer>
<% end %>

app/views/layouts/_navbar.html.erb
<% if controller_name == "pages" && !user_signed_in?%>
<nav>
  <div class="grey lighten-5 nav-wrapper">
    <a href="#!" class="brand-logo" style="margin-left:50px;"><%= image_tag("BleedMe_Landscape.png", :alt => "logo", size:"170x60") %></a>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to 'Inicio', root_path, class:"pink-text text"%></li>
      <li><%= link_to 'Conócenos', about_path, class:"pink-text text"%></li>
      <li><%= link_to 'Donaciones', donations_path, class:"pink-text text"%></li>
      <li><%= link_to 'Noticias y Campañas', news_path, class:"pink-text text"%></li>
      <li><%= link_to 'Contáctenos', contact_path, class:"pink-text text"%></li>
      <li><%= link_to 'Iniciar Sesion', new_user_session_path, class:"pink"%></li>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <li><%= link_to 'Inicio', root_path%></li>
      <li><%= link_to 'Conócenos', root_path%></li>
      <li><%= link_to 'Donaciones', donations_path%></li>
      <li><%= link_to 'Noticias y Campañas', news_path%></li>
      <li><%= link_to 'Contáctenos', contact_path%></li>
      <li><%= link_to 'Iniciar Sesion', new_user_session_path, class:"pink"%></li>
    </ul>
  </div>
</nav>
<% elsif user_signed_in? %>
<ul id="dropdown1" class="dropdown-content">
  <li><%=link_to 'Ver Solicitudes', requests_path, class:"pink-text text"%></li>
  <li><%=link_to 'Nueva Solicitud', new_request_path, class:"pink-text text"%></li>
  <li class="divider"></li>
</ul>
<nav>
  <div class="grey lighten-5 nav-wrapper">
    <a href="#!" class="brand-logo" style="margin-left:50px;"><%= image_tag("BleedMe_Landscape.png", :alt => "logo", size:"170x60") %></a>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to 'Timeline', posts_path, class:"pink-text text"%></li>
      <li><a class="dropdown-button pink-text text" data-activates="dropdown1">Solicitudes de Sangre<i class="material-icons right">arrow_drop_down</i></a></li>
      <li><a class="pink-text text modal-trigger" href="#modal1">Crear un Post</a></li>
      <li><%= link_to 'Mi Perfil', profiles_path, class:"pink-text text"%></li>
      <li><%= link_to('Cerrar Sesion', destroy_user_session_path, :method => :delete, class:"pink") %></li>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <li><%= link_to 'Timeline', root_path, class:"pink-text text"%></li>
      <li><%= link_to 'Solicitudes de Sangre', about_path, class:"pink-text text"%></li>
      <li><%= link_to 'Crear un Post', news_path, class:"pink-text text"%></li>
      <li><%= link_to 'Mi Perfil', profiles_path, class:"pink-text text"%></li>
      <li><%= link_to('Cerrar Sesion', destroy_user_session_path, :method => :delete, class:"pink") %></li>
    </ul>
  </div>
</nav>
<%end%>

<!-- Modal Structure -->
<div id="modal1" class="modal">
  <div class="modal-content">
    <h4>Nuevo Post</h4>
    <%= form_for(Post.new) do |f| %>
    <div class="row">
      <div class="input-field col s12">
        <i class="material-icons prefix">mode_edit</i>
        <%= f.label :body, "Escribe un post" %>
        <%= f.text_area :body, class:"materialize-textarea" %>
      </div>
    </div>
    <div class="row">
      <div class="col s12 center">
        <%= f.submit "Aceptar", class:"btn pink modal-action modal-close" %>
      </div>
    </div>
    <%end%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BleedMe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<%= yield %>
<%= render 'layouts/footer' %>
</body>

<script>
  $(document).ready(function(){
    $('.slider').slider({full_width: true});
    $('select').material_select();
    $('.datepicker').pickadate({
        selectMonths: true, // Creates a dropdown to control month
        selectYears: 300 // Creates a dropdown of 116 years to control year
      });
    $('.modal-trigger').leanModal();
    $('ul.tabs').tabs('select_tab', 'tab_id');
    $('ul.tabs').tabs();
    $('.dropdown-button').dropdown({
    inDuration: 300,
    outDuration: 225,
    constrain_width: false, // Does not change width of dropdown to that of the activator
    hover: true, // Activate on hover
    gutter: 0, // Spacing from edge
    belowOrigin: false, // Displays dropdown below the button
    alignment: 'left' // Displays dropdown with edge aligned to the left of button
  }
);
  });
</script>
</html>